/* Iman Cleaning — homepage content. Service names & prices mirror the live
   site exactly (do not diverge). Everything else is conversion-focused copy. */
window.IMAN_DATA = {
  phone: "929-803-4053",
  phoneHref: "tel:+19298034053",
  googleReviewsHref: "https://share.google/EAX7wC22J4PyMKcNx",
  nav: [
    { label: "Services", href: "#services" },
    { label: "How it works", href: "#how" },
    { label: "Why us", href: "#why" },
    { label: "Service areas", href: "#areas" },
    { label: "FAQs", href: "./faq.html" },
  ],
  services: [
    {
      title: "Standard Cleaning",
      price: "Starting at $200",
      image: "./home-hero-clean-living-room.jpg",
      blurb: "Regular upkeep that keeps your home reliably fresh between visits.",
      points: ["Kitchens, baths, bedrooms & living areas", "Weekly, biweekly, monthly, or one-time"],
      href: "./standard-cleaning.html",
    },
    {
      title: "Deep Cleaning",
      price: "Starting at $300",
      image: "./contact-kitchen-hero.jpg",
      blurb: "First-time cleanings, seasonal resets, and heavier buildup.",
      points: ["Detailed high-touch & neglected areas", "Photos help us size the team accurately"],
      href: "./deep-cleaning.html",
      featured: true,
    },
    {
      title: "Move-In / Move-Out",
      price: "Starting at $300",
      image: "./home-hero-team.jpg",
      blurb: "A clean handoff for apartments, homes, and rental turnovers.",
      points: ["Empty-space cleaning for leases", "Ideal before photos, staging, or keys"],
      href: "./move-in-move-out-cleaning.html",
    },
    {
      title: "Office & Commercial",
      price: "Custom quote",
      image: "./home-hero-clean-living-room.jpg",
      blurb: "Offices, retail, clinics, restaurants, and recurring janitorial.",
      points: ["Walkthroughs for larger spaces", "Recurring janitorial options available"],
      href: "./commercial-cleaning.html",
    },
  ],
  steps: [
    { n: "01", title: "Request your quote", body: "Send your details online or call us. Add photos of the space so we can quote accurately." },
    { n: "02", title: "We confirm everything", body: "We call you back to review the scope, timing, and exact price — so it's all clear before you commit." },
    { n: "03", title: "Approve & pay", body: "Happy with the quote? Confirm and pay to lock in your appointment for the day that works for you." },
    { n: "04", title: "We clean, you relax", body: "On the scheduled day, an insured Iman crew arrives on time and leaves the space spotless." },
  ],
  reasons: [
    { icon: "shield", title: "Fully Insured Team", body: "Reliable cleaning professionals who treat your home or business with care." },
    { icon: "quote", title: "Clear Upfront Pricing", body: "Know your price before service begins—no hidden fees or surprise charges." },
    { icon: "sparkle", title: "Supplies Included", body: "We bring the professional products and equipment needed for your cleaning." },
    { icon: "heart", title: "Satisfaction Promise", body: "Notice something we missed? Tell us before we leave, and we'll make it right." },
  ],
  serviceCategories: [
    {
      title: "Residential Cleaning", kicker: "Homes & apartments",
      image: "./assets/home-residential-cleaning-card.webp",
      imageAlt: "Professionally cleaned residential living room",
      imageWidth: 900,
      imageHeight: 600,
      services: [
        { name: "Standard Cleaning", price: "$200", href: "./standard-cleaning.html" },
        { name: "Deep Cleaning", price: "$300", href: "./deep-cleaning.html" },
        { name: "Move-In / Move-Out", price: "$300", href: "./move-in-move-out-cleaning.html" },
        { name: "Detailed Cleaning", price: "Custom quote available", href: "./details-cleaning.html" },
        { name: "Extreme Cleaning", price: "Custom quote available", href: "./extreme-cleaning.html" },
        { name: "Organization Services", price: "$60 per labor-hour · 4 labor-hour minimum", href: "./organization-services.html" },
      ],
    },
    {
      title: "Commercial Cleaning", kicker: "Offices & businesses",
      image: "./assets/home-commercial-cleaning-card.webp",
      imageAlt: "Professionally cleaned commercial restaurant interior",
      imageWidth: 900,
      imageHeight: 720,
      services: [
        { name: "Office Cleaning", price: "Custom quote", href: "./office-cleaning.html" },
        { name: "Retail Store Cleaning", price: "Custom quote", href: "./retail-store-cleaning.html" },
        { name: "Restaurant Cleaning", price: "Custom quote", href: "./restaurant-cleaning.html" },
        { name: "Medical & Clinic Cleaning", price: "Custom quote", href: "./medical-clinic-cleaning.html" },
        { name: "Janitorial / Recurring Cleaning", price: "Custom quote", href: "./janitorial-recurring-cleaning.html" },
      ],
    },
    {
      title: "Window Cleaning", kicker: "Homes & businesses",
      image: "./assets/home-window-cleaning-card.webp",
      imageAlt: "Professional window cleaning with a squeegee",
      imageWidth: 900,
      imageHeight: 675,
      services: [
        { name: "Interior & Exterior Glass", price: "Custom quote", href: "./quote.html?service=window-cleaning" },
        { name: "Frames, Sills & Tracks", price: "Custom quote", href: "./quote.html?service=window-cleaning" },
        { name: "Homes & Apartments", price: "Custom quote", href: "./quote.html?service=window-cleaning" },
        { name: "Offices & Storefronts", price: "Custom quote", href: "./quote.html?service=window-cleaning" },
      ],
    },
  ],
  serviceAreas: [
    { name: "Manhattan" },
    { name: "Brooklyn" },
    { name: "Queens", href: "./cleaning-services-nyc.html#queens-cleaning" },
    { name: "The Bronx" },
    { name: "Staten Island" },
  ],
  boroughs: ["Manhattan", "Brooklyn", "Queens", "The Bronx", "Staten Island"],
  faqs: [
    { q: "Do I get a price before the appointment is confirmed?", a: "Yes. We provide an estimated price before your appointment is confirmed. In many cases, we can give you a quote based on the information you provide. For homes that require additional evaluation, we may request photos or schedule a walkthrough before confirming the final price. You'll know the cost before your appointment is officially booked.", open: true },
    { q: "Do you clean in all five NYC boroughs?", a: "Yes. Iman Cleaning Service proudly serves Manhattan, Brooklyn, Queens, The Bronx, and Staten Island. If you're unsure whether your location falls within our service area, contact us and we'll be happy to confirm." },
    { q: "Can I request commercial cleaning?", a: "Absolutely. We provide professional commercial cleaning services for offices, retail stores, restaurants, medical facilities, apartment buildings, and other businesses. We offer one-time, recurring, and customized cleaning plans based on your property's needs. Contact us for a custom quote." },
    { q: "What should I include in my quote request?", a: "To provide the most accurate estimate, include as much information as possible: the property address or ZIP code, type of cleaning service, number of bedrooms and bathrooms or square footage, current condition, requested add-ons, preferred date and time, and photos if available. Providing detailed information helps us prepare an accurate quote and avoid delays." },
    { q: "What hours are available?", a: "Our scheduling varies based on availability. We offer appointments throughout the week, including weekends when available. Morning, afternoon, and evening appointments may be offered depending on our schedule. If you need a specific time, we recommend booking as early as possible." },
    { q: "Why is Iman priced higher than a typical cleaning service?", a: "We focus on delivering professional, reliable, and high-quality cleaning rather than offering the lowest price. Our pricing reflects the time, attention to detail, trained staff, professional equipment, insurance coverage, and customer service that go into every appointment. We don't rush through jobs or promise several hours of work for an unrealistically low price. Our goal is to provide consistent results, honest pricing, and a service you can rely on." },
    { q: "My budget is low — is Iman right for me?", a: "We understand that every customer has a different budget. If you're looking for the lowest possible price, we may not be the best fit. Our focus is on providing dependable, professional cleaning with fair pricing that reflects the quality of our work. If your budget is limited, let us know. We may be able to recommend a smaller scope of work or prioritize the areas that matter most, allowing you to stay within your budget while still receiving professional service." },
  ],
  review: {
    name: "Verified Google review",
    text: "They did a great job cleaning my house. They showed up on time, were friendly, and paid attention to the little things. My place looked and smelled so much better when they were done. Definitely worth it, and I’d use them again.",
    author: "Mahin Muhtasimul",
  },
};
